// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fajaeeurxppwdnsuzfgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhamFlZXVyeHBwd2Ruc3V6ZmdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDEzMTksImV4cCI6MjA1ODgxNzMxOX0.r9sUPREKpYBDuCsJQI7UjF-PhbGzhbBByC0-xHLB8Wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);